- docs/Dockerfile
> Updating to use the latest image

- docs/governance/board-profiles.md
- docs/governance/dgab-info.md
Signed-off-by: spf13 <steve.francia@gmail.com>
> updating DGAB to 2015

- docs/how-to-contribute.md
Signed-off-by: Xiaohui Liu <xiaohui.zju@gmail.com>
> remove the duplicated description of docker/distribute project

- docs/governance/conduct-code.md
> Fixes #17 broken link

- docs/governance/conduct-code.md
> Fix errant link

- docs/governance/index.md
- docs/workflow/index.md
> Fixing the build

- docs/project/set-up-git.md
From docker/docker#17565, @pmalmgren (Peter Malmgren <ptmalmgren@gmail.com>).
/ping @moxiegirl 
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Added additional guidance for signing off git commits when contributing.

- docs/Dockerfile
> Use the build cache for the svn checkouts of the other projects

- docs/Dockerfile
- docs/kitematic/set_up_dev.md
- docs/workflow/advanced-contributing.md
- docs/workflow/coding-style.md
> Use FROM docs/base:latest again

- docs/workflow/find-an-issue.md
carry of @lyndaoleary's PR https://github.com/docker/docker/pull/17254
closes https://github.com/docker/docker/issues/16156
> [carry] update "find an issue" with new labels

- maintainers/main.go
Looks like this one was missing
> Add spdystream

- docs/code.md
Signed-off-by: Katrina Owen <katrina.owen@gmail.com>
> fix typo in code documentation

- MAINTAINERS
- maintainercollector/main.go
depends on https://github.com/docker/containerd/pull/42
ping @crosbymichael @jfrazelle
> Add containerd

- docs/project/set-up-dev-env.md
Fixes: #18698
Signed-off-by: Kai Qiang Wu(Kennan) <wkqwu@cn.ibm.com>
> Add explanation for unexpected error msg

- MAINTAINERS
- maintainercollector/main.go
> Add go-plugins-helpers and update maintainers

- docs/Dockerfile
- docs/workflow/create-pr.md
> Fixing duplicate ids for 1.10

- docs/kitematic/set_up_dev.md
> Fix broken URL

- MAINTAINERS
- maintainercollector/main.go
> Add docker/leadership repo

- MAINTAINERS
Chun Chen was added as a maintainer
> Update libnetwork maintainers

- docs/Dockerfile
- docs/get-help.md
- docs/ways/community.md
@thaJeztah @sanscontext
Review this please.
> Removing links to old Google groups

- project-template/CONTRIBUTING.md
- project-template/INSTRUCTIONS.md
- project-template/LICENSE.code
- project-template/LICENSE.docs
- project-template/MAINTAINERS
- project-template/README.md
closes https://github.com/docker/opensource/issues/44
This adds a basic project template that can be used to set up new open source projects.
> Add project template

- MAINTAINERS
- maintainercollector/main.go
> Update maintainers with new open source projects

- MAINTAINERS
- maintainercollector/main.go
ping @stevvooe @FrenchBen PTAL
> Add go-p9p project to maintainers file

- docs/project/set-up-git.md
Signed-off-by: nirmalmehta <nirmalkmehta@gmail.com>
> fixed escape of bullet item so code block renders properly

- MAINTAINERS
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
> Update Swarm maintainers

- docs/Dockerfile
- docs/Makefile
- docs/get-help.md
- docs/ways/community.md
- docs/workflow/coding-style.md
> fix urls found by linkchecker, and clean up tooling

- MAINTAINERS
- maintainercollector/main.go
> Add docker-credential-helpers and update libcompose maintainers

- MAINTAINERS
- maintainercollector/main.go
Signed-off-by: Bill Farner <bill@docker.com>
> Add infrakit.aws

- MAINTAINERS
- maintainercollector/roles.toml
Assigning myself and Victor as this role
is now covered between us.
Information about docker community can
also be found in a dedicated repository;
https://github.com/docker/community
> Update "Community Manager" role
